spring.application.name=parking

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/parking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota}
spring.datasource.username=${DB_USERNAME:parking_user}
spring.datasource.password=${DB_PASSWORD:Parking123!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=info

spring.main.banner-mode=off

app.auth.username=${APP_AUTH_USERNAME:admin}
app.auth.password=${APP_AUTH_PASSWORD:change-me}
